spring:
  application:
    name: OA
  datasource:
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1234

server:
  port: 10001

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.damon.oa.model
